### ISSUE TITLE
ASpace id resolver incorrectly assumes a "object" type

### ISSUE THREAD

**Issue by ctgraham** [RockefellerArchiveCenter/request_broker#216]
## Describe the bug
When resolving an ASpace Id to a URI, the path of "object" is hardcoded, but not guaranteed:
https://github.com/RockefellerArchiveCenter/request_broker/blob/ad0bc3c3101147760cdb43f322f8da6c3c7c1c75/process_request/views.py#L126-L127

## To reproduce
1. Try resolving: https://dimes.rockarch.org/request-broker/process-request/resolve?ref_id=284cfabdceeb423197dec40c4145ca84
2. Referred to: https://dimes.rockarch.org/objects/NAAxXgmHDptFfFiapTuSVh
3. Correct URL is: https://dimes.rockarch.org/collections/NAAxXgmHDptFfFiapTuSVh

## Expected behavior
The `LinkResolverView` or the `resolve_ref_id` helper will need to inspect the object to determine the object type.

## Error message or screenshots
See steps to reproduce.

## Impact on your work
The existing code will route users to a 404 with links at the component (collection) level.

## Additional context
n/a

**Comment by helrond** [comment]
Thanks @ctgraham I should have caught this one earlier!

Check out #217 and see if that works for you.
