### ISSUE TITLE
Remove HTML / XML from Aeon POSTs

### ISSUE THREAD

**Issue by ctgraham** [RockefellerArchiveCenter/request_broker#221]
## Describe the bug
Aeon does not support receiving HTML / XML in POST data.  If encountered, it will respond with a 500 stating:
```
Server Error in '/Logon' Application.
Runtime Error 
```

Matt Calsada from Atlas Systems reports:
>We can add a bug for this. Out of curiosity, what is the use case for the HTML/XML tags that you are passing in to your Aeon ItemInfo1 fields from the EAD? Is this just a one-off EAD that may have tags in it or do all of Pitt's EAD's have markup in the EAD that you'd be passing into Aeon. In general, we (and the ASP.NET defaults) don't support this as it is seen as a security risk, primarily as cross-site scripting concerns. We wouldn't display the tags in any web user interfaces. 

In the meantime, we thought that stripping these tags in Pisces indexing would mitigate both the display in DIMES and the submission to Aeon:

https://github.com/RockefellerArchiveCenter/pisces/issues/507
https://github.com/RockefellerArchiveCenter/pisces/issues/508

As it turns out, however, the Request Broker is pulling data directly from ASpace rather than using Elastic data.

https://github.com/RockefellerArchiveCenter/request_broker/blob/9fc371944a231181f98fec90d29f9e7521e9cd9b/process_request/routines.py#L17-L73

## To reproduce
1. Edit the title of any ASpace object to include HTML or XML
2. POST that item identifier to the `api/deliver-request/reading-room` endpoint
3. Atlas-Systems hosted Aeon will respond with a 500

## Expected behavior
This really is, at core, an Aeon bug in preferring to raise an error in ASP.net rather than properly escaping HTML in the public UI.

But, in as a mitigation, it is reasonable to follow our strategy in pisces to strip HTML / XML.

## Error message or screenshots
C.f. Description

## Impact on your work
Objects with XML/HTML will cause requests to fail for end-users, with no clear messaging for cause or resolution.

## Additional context

There may be a data leakage risk as nothing in the call stack checks to see if an item is indexed in Elastic before making the API call to ASpace and returning the request data.  The indexing restrictions implemented in pisces such as [prefix or status restrictions](https://github.com/RockefellerArchiveCenter/pisces/blob/91434d942850b39b48ae3308683a941d9eda266e/pisces/config.py.example#L27-L28) may protect sensitive resources, where public exposure is unwanted.

**Comment by helrond** [comment]
@ctgraham would your proposal be to implement the same `strip_tags` method we use [here](https://github.com/RockefellerArchiveCenter/pisces/blob/6f75fd49e51c7f1bd37ba4e948756405ea2cf8a6/transformer/mappings.py#L56-L64)?

Regarding:

> There may be a data leakage risk as nothing in the call stack checks to see if an item is indexed in Elastic before making the API call to ASpace and returning the request data. The indexing restrictions implemented in pisces such as [prefix or status restrictions](https://github.com/RockefellerArchiveCenter/pisces/blob/91434d942850b39b48ae3308683a941d9eda266e/pisces/config.py.example#L27-L28) may protect sensitive resources, where public exposure is unwanted.

That is technically true in the Request Broker context HOWEVER when requesting data from DIMES the `PageMyList` component has to fetch that data from the API, then provide the ArchivesSpace URI to the Request Broker: https://github.com/RockefellerArchiveCenter/dimes/blob/base/src/components/PageMyList/index.js#L41

**Comment by ctgraham** [comment]
The `strip_tags` method is my leading candidate for a workaround.

Regarding the data leak, an abusive actor would have to know or guess the ASpace IDs for the restricted records, then use the request-broker endpoint directly.  On the other hand, however, it would be pretty trivial to look at known ASpace IDs fetched from valid requests, and interpolate missing IDs and then query on those.  These records are protected behind the ASpace API, but the request broker can inadvertently serve as a proxy to bypass this protection.

**Comment by helrond** [comment]
Crucial detail I forgot to mention - we run our Request Broker instance behind our firewall, and restrict traffic to it from only the DIMES server, not only for the reasons you articulate but also because it returns location information. I'm reluctant to couple the Request Broker too tightly to the Argo API, because I think that takes away some of its usefulness as a service. If you have ideas for how to improve security I'm all ears though!

I'm fine with the `strip_tags` approach as a workaround.

**Comment by ctgraham** [comment]
Even though the request broker is not directly exposed, it is exposed by proxy through DIMES, and thus the proxy to ASpace is still present.  I'll send additional details privately.
