### ISSUE TITLE
Process full identifier to resource_id field

### ISSUE THREAD

**Issue by ctgraham** [RockefellerArchiveCenter/request_broker#222]
## Is your feature request related to a problem? Please describe.
Currently, the resource_id consists only of the first ID component from ASpace:
https://github.com/RockefellerArchiveCenter/request_broker/blob/9fc371944a231181f98fec90d29f9e7521e9cd9b/process_request/routines.py#L56

ASpace provides fields for the identifier by component parts, as specified in DACS 2.1.3:
https://saa-ts-dacs.github.io/dacs/06_part_I/03_chapter_02/01_reference_code.html#local-identifier

## Describe the solution you'd like
Concatenate all available local identifiers (ASpace JSON fields `id_0`, `id_1`, `id_2`, `id_3`) to form the `resource_id`.

## Describe alternatives you've considered
Create additional named properties for each component part in the object data?  Seems unhelpful and unnecessary.

## Additional context
We use "." for our separator, but it looks like DACS 2.1.3 allows for other separators, like space or hyphen.  Should this be a configuration option?

**Comment by helrond** [comment]
Good call - it looks like there is something in [ArchivesSnake](https://github.com/archivesspace-labs/ArchivesSnake/blob/master/asnake/utils/__init__.py#L149-L166) which does this so that's an easy add. And agree on making the separator a config value.
