### ISSUE TITLE
Provide production-ready dockerfile

### ISSUE THREAD

**Issue by ctgraham** [RockefellerArchiveCenter/request_broker#241]
## Is your feature request related to a problem? Please describe.
We intend to provide a single docker-compose.yml which (when configured with environment variables) can spin up a production stack.  Each microservice will have a production Dockerfile which builds a production container, ready to be proxied to the world through a frontend of apache, nginx, or (by default) traefik.

## Describe the solution you'd like
An Apache + WSGI deployment of the Django application on a single port and name.

## Describe alternatives you've considered
n/a

## Additional context
N.b.: anticipated configuration will establish a canonical DNS name, but listen for any Host header, so production access will still be possible via SSH port-forward over localhost, and intercontainer communication via the container name.

**Comment by Tyl13** [comment]
Chrysanthemum's PR #299 already included all of these commits.
