### ISSUE TITLE
Create representation of request data prior to submission

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/request_broker#26]
## Is your feature request related to a problem? Please describe.
In order to move development forward, it would be helpful to have a sense of what data should look like prior to submission (i.e. what `ProcessRequest().run()` produces).

## Describe the solution you'd like
A static representation of request data, ideally as fixtures that could be pulled into unit tests. This could initially be done by looking at the fields that Aeon captures.

Ultimately we'll probably want to codify this in a JSON Schema so we can validate inputs and outputs.

**Comment by p-galligan** [comment]
Example of data required from as in `fixtures/as_data.json`.
