### ISSUE TITLE
Allow location field (Aeon) to be represented by the location title (ArchiveSpaceAPI)

### ISSUE THREAD

**Issue by kcloud** [RockefellerArchiveCenter/request_broker#293]
## Is your feature request related to a problem? Please describe.
Currently the request broker generates a short location field `make_short_location` mapped to Aeon for Rockefeller Center preferences.

## Describe the solution you'd like
A method to distinguish between field preferences for location. This should reflect the ArchiveSpaceAPI.

## Describe alternatives you've considered
Both https://github.com/RockefellerArchiveCenter/request_broker/issues/228 and https://github.com/RockefellerArchiveCenter/request_broker/issues/240 address customization alternatives that have been considered. This change may be temporary pending changes to either of those issues.

## Additional context
See above for customization context.

**Comment by helrond** [comment]
closed by #295
