### ISSUE TITLE
Fetch additional data from ArchivesSpace

### ISSUE THREAD

**Issue by p-galligan** [RockefellerArchiveCenter/request_broker#33]
## Is your feature request related to a problem? Please describe.
Reading room and duplication requests to Aeon should include information that you can't find from a single object in ArchivesSpace. We will need to interact with a few different AS endpoints to gather this information or use the `resolved` parameter to fetch additional data.

## Describe the solution you'd like
These fields are required:
creator: records creator.
barcode: barcode for top container that an object is housed in
collection name: Title of the resource record containing the object
aggregation: Title of the Series or Record Group containing the object (if one exists)
dates: Dates of the object, if no date associated with object, next closest parent date.
location: Housing location of the object at RAC
resource id: Resource id of the collection housing an object. Generally id_0
container: Concatenated data indicating Box and number for object. Ex.: "Box 1" or "Reel 3"
title: object display string
restrictions: Human readable string of any restrictions associated with an object. Inherit closest restrictions if they exist
url: ArchivesSpace ref of requested object

## Additional context
We may need to expand or reduce this in the future, but these represent the major fields we'll need from AS. You may also decide to remove or add methods as necessary/as you like.

**Comment by bonniegee** [comment]
Two questions about the data we're getting from AS:

- We always want the aggregation closest to the resource, right? (I.e., if an item has 4 ancestors, we  want the one right below the resource.)
- For collection creator, can we reliably assume each collection has only one linked agent with the role of creator? If there are multiple, should it be handled by combining all of them, or picking one?

**Comment by p-galligan** [comment]
- I think it depends on the data you're interested in. If you're just looking for an aggregation, I'd say the first one below the resource level, but it may be possible to grab all and concatenate them. Though I'm not sure that's helpful if we have a link to the requested item already. For dates and restrictions, we'd want the closest data above the item.
- Collections sometimes have multiple creators. I wouldn't mind @helrond 's take, but I think it could go a couple of ways. One, we could grab all creators and put them in the same field separated by commas, or just grab one and pass that along. For Aeon purposes, we've only sent a single creator in the past, as far as I know.

**Comment by helrond** [comment]
Yes, the "aggregation" can just be the immediate ancestor. Side note, you'll likely need to get data for all the ancestors anyway, in order to check restrictions and such.

I think let's grab all the creators.

**Comment by bonniegee** [comment]
Just to confirm - if an object doesn't have a title, we want to use the display string?

**Comment by p-galligan** [comment]
To answer your question, I think using the display string in all cases might be the most preferable, as long as we don't mind the date being included when one is present. We already show the display string in DIMES as it is.

**Comment by bonniegee** [comment]
For the restrictions data, would it be useful to have the boolean as well, or just record the note text?

**Comment by p-galligan** [comment]
Based on the slack convo with @helrond , yes, I think we should expand to have a restrictions apply field, thought I think it may need to be more than Boolean to account for “conditional” statements.

**Comment by bonniegee** [comment]
Okay; so for the restrictions apply field, first I'll check whether "restrictions_apply" is True; if it's False, I'll still use matching against note text to check whether something is restricted.

**Comment by p-galligan** [comment]
Yes, and matching against premis rights statements as well.

**Comment by bonniegee** [comment]
If there's no linked agent with the role of creator attached to a resource, do we want to throw an error or just have a blank field?

**Comment by p-galligan** [comment]
I would say leave it blank. But also, that really shouldn't happen, even though we know it's possible.

**Comment by p-galligan** [comment]
Going to leave this open pending closure of PR #52
