### ISSUE TITLE
Update requirements.txt file.

### ISSUE THREAD

**Issue by helrond** [RockefellerArchiveCenter/request_broker#47]
## Is your feature request related to a problem? Please describe.
The `requirements.txt` file does not have a full list of all of the app's dependencies.

## Describe the solution you'd like
Update requirements.txt (using `pip freeze`) with a complete list of dependencies.

**Comment by p-galligan** [comment]
Gonna wait on this one for a bit until outstanding PRs are pulled in because there are some differences between them.
