### ISSUE TITLE
Tests are not running properly when Django nose is enabled

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/request_broker#63]
## Describe the bug
When running tests with Django nose, it appears that tests run correctly. However, in the docker console, it's clear that the test database was not created:
```
request-broker-db_1   | 2020-11-09 19:22:27.945 UTC [39] FATAL:  database "test_postgres" does not exist
```
When commenting out the test runner in settings.py, the tests ran fine.

## To reproduce
Compare the logs and test results when running tests with and without Django nose

## Expected behavior
The test database is created successfully and tests run as intended.

## Additional context
When the tests ran as intended, it looks like some of the tests had extraneous print statements that can be removed.

**Comment by helrond** [comment]
@bonniegee IIRC we did this so we could get a coverage report when running tests. Is there an alternative strategy for getting those reports if we don't use nose?

**Comment by bonniegee** [comment]
Yep! The approach I've used with Aquila is coverage: https://adamj.eu/tech/2019/04/30/getting-a-django-application-to-100-percent-coverage/
