### ISSUE TITLE
Restrictions check not working for all restricted material

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/request_broker#69]
## Describe the bug
Restrictions check not working for all restricted material. 

## To reproduce
In DIMES, this object can be requested with no set restrictions:
- objects/QYWj9e74hzsia7Fj9JpHhi 

The item is noted as restricted via a a Conditions Governing Use subnote: "Restricted from scholarly access."

**Comment by helrond** [comment]
OH I SEE WHY THIS IS. Request Broker is looking at `accessrestrict` notes for access restrictions, but this is a `userestrict` note. I updated the note type so this should work now.
