### ISSUE TITLE
Improve usefulness of CSV data

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/request_broker#80]
## Is your feature request related to a problem? Please describe.
Like in the emails (see issue #79), Reference staff has requested changes to the CSV fields.

## Describe the solution you'd like
Continue to use the same export fields as the emails, which means remove:
- restriction_text
- resource_id
- containers
- uri

Add:
- size (extent)
- DIMES URL for the object

Change:
- Do not inherit dates from parent components
- Consider concatenating the item title and dates

**Comment by helrond** [comment]
@bonniegee I believe you wrote the `get_dates` helper? Do you remember why we pulled in dates from ancestor components?

**Comment by bonniegee** [comment]
In issue #33, we articulated a requirement to get the date of the closest ancestor if a component didn't have a date. I.e., in order to not have blank dates we use the ancestor date. I can't speak to the reason for that (like if it's useful for Aeon to have to generate the citation sheet or whatever).

**Comment by helrond** [comment]
OK, I'm not seeing anything in the [RFC](https://github.com/RockefellerArchiveCenter/project_electron/blob/base/rfcs/006-request-broker-service.md) or any of the other spec documents so I think this may have just been an inadvertent spec. I've removed date inheritance #84, but tagging @p-galligan in to see if he has any objection before I merge.

**Comment by p-galligan** [comment]
I’m not finding any explicit documentation or references to dates in Slack messages with @helrond around the time of this Issue. It was probably an inadvertent inclusion as identified. 

No objections here.
